# Testing the code base against a specific Meilisearch feature
name: Beta tests

# Will only run for PRs and pushes to *-beta
on:
  push:
    branches: ['!bump-meilisearch-v*.*.*-beta', '**-beta']
  pull_request:
    branches: ['!bump-meilisearch-v*.*.*-beta', '**-beta']

jobs:
  meilisearch-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.grep-step.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Grep docker beta version of Meilisearch
        id: grep-step
        run: |
          MEILISEARCH_VERSION=$(sh .github/scripts/beta-docker-version.sh)
          echo $MEILISEARCH_VERSION
          echo ::set-output name=version::$MEILISEARCH_VERSION
  integration_tests:
    runs-on: ubuntu-latest
    needs: ['meilisearch-version']
    services:
      meilisearch:
        image: getmeili/meilisearch:${{ needs.meilisearch-version.outputs.version }}
        env:
          MEILI_MASTER_KEY: 'masterKey'
          MEILI_NO_ANALYTICS: 'true'
        ports:
          - '7700:7700'
    strategy:
      matrix:
        node: ['14', '16', '18']
    name: integration-tests (Node.js ${{ matrix.node }})
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - name: Install dependencies
        run: yarn --dev
      - name: Run tests
        run: yarn test
      - name: Build project
        run: yarn build
      - name: Run ESM env
        run: yarn test:env:esm
      - name: Run Node.js env
        run: yarn test:env:nodejs
      - name: Run node typescript env
        run: yarn test:env:node-ts
      - name: Run Browser env
        run: yarn test:env:browser
